Adds extention and default value for shader functions
hazzard993/love-typescript-definitions pull request #68
Opened 2022-09-25 18:41 UTC by xharris

I was seeing this error when compiling with `tstl`.
```
[{
	"resource": "****/node_modules/love-typescript-definitions/typings/love.graphics/functions.d.ts",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'T' does not satisfy the constraint '{ [key: string]: any; } | undefined'.\n  Type 'T' is not assignable to type '{ [key: string]: any; }'.",
	"source": "ts",
	"startLineNumber": 1310,
	"startColumn": 61,
	"endLineNumber": 1310,
	"endColumn": 62,
	"relatedInformation": [
		{
			"startLineNumber": 1310,
			"startColumn": 24,
			"endLineNumber": 1310,
			"endColumn": 37,
			"message": "This type parameter might need an `extends { [key: string]: any; }` constraint.",
			"resource": "****/node_modules/love-typescript-definitions/typings/love.graphics/functions.d.ts"
		},
		{
			"startLineNumber": 1310,
			"startColumn": 24,
			"endLineNumber": 1310,
			"endColumn": 37,
			"message": "This type parameter might need an `extends { [key: string]: any; } | undefined` constraint.",
			"resource": "****/node_modules/love-typescript-definitions/typings/love.graphics/functions.d.ts"
		}
	]
}]
```
My changes seem to fix this error.

2022-09-25 22:59 UTC, hazzard993 requested changes
Thanks for highlighting this issue!

See my review comment and I'm happy to merge after

2022-09-25 22:59 UTC, hazzard993 commented on typings/love.graphics/functions.d.ts
> +    function newShader<T extends {[key:string]:any} = {}>(code: string): Shader<T>;
```suggestion
    function newShader<T extends {[key:string]:any} = { [key: string]: any }>(code: string): Shader<T>;
```

A default constraint of `{ [key: string]: any }` will allow users to continue to use the following code:

```ts
const shader = love.graphics.newShader("...");
shader.send("myUniform", 0);
```

If you could apply this change to line 1330 and run `yarn fix:prettier` I'm happy to get this merged and released

2022-09-26 16:07 UTC, xharris commented
All done. Thanks for reviewing!

2022-09-27 02:10 UTC, merged

2022-09-27 02:15 UTC, hazzard993 commented
Excellent! Your changes should now be available in `love-typescript-definitions@0.24.3`